### ISSUE TITLE
Problem in case of sampling replay memory

### ISSUE THREAD

**Issue by ayushri117** [fsan/dqn_-brthor#1]
While running the exact code, i am running into the error:

observations = np.asarray([t[0] for t in transitions], dtype=np.float32)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (32,) + inhomogeneous part.

**Comment by fsan** [comment]
There is quite some done I have worked on this, but by coincidence, I ran this code yesterday and it seemed to be fine for me.

What I suspect is that your dependencies are different. You may want to check the python version too.
I do not know if you are familiar with pipenv, but this project uses it for managing dependencies.

If you need to install it, you can do it at pipenv.pypa.io
To install the dependencies, run `pipenv sync --dev`
I manage my python versions using `asdf` in Linux as `pyenv` on Mac. Anyway you do it, should be fine as long as pipenv can find the correct python version in your path.

Another thing you might want to look is that openai have deprecated gym packages. I have not tested it with gymnasium version.
In any case, if you sync using pipenv lock file provided it should work fine if you have a GPU.
If you don't, you might just remove the .cuda() calls from the code.


I hope that helps you figure it out what's going on. See you!

EDIT: If you find the solution please share it here to help other in the future.

**Comment by ayushri117** [comment]
I did what you suggested, it seems to run for the training part, but throws an error  while rendering, stating Module not found for pygame and gym[classic control], and when i run the following ```pipenv install pygame gym[classic control]``` it throws an error stating failed to install dependencies

**Comment by fsan** [comment]
Which module? Do you have the log error message?

I think you should also try running PyGame examples to check if it is not an installation problem. Usually PyGame spits some logs indicating you are missing some native dependencies.

```bash
pipenv run python3 -m pygame.examples.aliens
```

I hope his helps you finding the problem. Please, share the solution with others  when you find it.

**Comment by ayushri117** [comment]
I found the solution, it was all because of gym :)
The code works fine for new python and gym version after making the following changes.

change ``` obs=env.reset()``` to ```obs, _=env.reset()``` reset function returns two values now, an array of observations and info.

You will also need to make other changes such as:
``` new_obs, reward, done, _,  = env.step(action)``` to ```new_obs, reward, done, _,_ = env.step(action)```

With above changes the code will run, but you wont be able to render the scene, when you will try to it will throw an error.

To overcome this you need to add ```render_mode=human``` (PS you can choose other render modes as well)

This should be added while making the environment:
```env = gym.make('CartPole-v1',render_mode="human")```

This will however slow down the training time, as it will render the scene during training as well.
If you don't want this to happen, you can run the script without render_mode for training and save the model weights, create another python file, load the model and make the environment with render_mode human, for visualizing the scene.

**Comment by fsan** [comment]
That's great to know! Thanks for sharing.

I think you shouldn't render while training, or you should render in a different thread by loading one save point.

What people usually do is to save several checkpoints and then execute them to capture footage
